version: "3"
services:
  todoapp1:
    image: todoapp:latest
    ports:
      - 9000:9000
    container_name: todo_container

  todoapp2:
    image: todoapp:latest
    ports:
      - 8000:9000
    container_name: todo_container2

  todoapp3:
    image: todoapp:latest
    ports:
      - 7000:9000
    container_name: todo_container3

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todoapp1
      - todoapp2
      - todoapp3
